pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - base=main
      - label=backport-to-stable
    actions:
      backport:
        branches:
          - V2016
          - V2017
          - V2018
          - V2019
          - V2020
          - V2021
          - V2022
        assignees:
          - "{{ author }}"
