package:
  name: abqpy
<<<<<<< HEAD
  version: 2021.1
=======
  version: "{{ GIT_DESCRIBE_TAG }}"
>>>>>>> 95f744e (Manage auto version from Git in Conda)

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True # [py<37]

source:
  git_url: https://github.com/haiiliin/abqpy.git
<<<<<<< HEAD
  git_rev: "v2021.1"
=======
  git_rev: "{{ GIT_DESCRIBE_TAG }}"
>>>>>>> 95f744e (Manage auto version from Git in Conda)

requirements:
  build:
    - python
  run:
    - python

test:
  import:
    - abaqus
    - mesh
    - abaqusConstants
about:
  summary: Type hints for Abaqus/Python scripting
  home: https://github.com/haiiliin/abqpy
  license: MIT
