package:
  name: abqpy
  version: "{{ GIT_DESCRIBE_TAG }}"

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  skip: True # [py<37]

source:
  git_url: https://github.com/haiiliin/abqpy.git
  git_rev: "{{ GIT_DESCRIBE_TAG }}"

requirements:
  build:
    - python
  run:
    - python

test:
  import:
    - abaqus
    - mesh
    - abaqusConstants
about:
  summary: Type hints for Abaqus/Python scripting
  home: https://github.com/haiiliin/abqpy
  license: MIT
